### PR TITLE
add nix shell support

### PR DESCRIPTION
**Pull request by skwerlman**

### CODE REVIEW

**Comment by skwerlman** [comment]
Please review this PR by starting a nix-shell on your machine using default.nix, and then compiling and testing in the shell.

```
cd belethor
nix-shell --pure
```
should be enough to get the shell started

in the shell, running
```
mix compile
```
should be enough to show its working

**Review by iggi42 — APPROVED** [review]
I get:
```
[user@dev-privat belethor]$ nix-shell --pure
bash: warning: setlocale: LC_CTYPE: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_COLLATE: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_MESSAGES: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_NUMERIC: cannot change locale (C.UTF-8): No such file or directory
bash: warning: setlocale: LC_TIME: cannot change locale (C.UTF-8): No such file or directory
```
does not impact anything thu, just a little annoying.

**Comment by skwerlman** [comment]
hmmm. what locales do you have on your machine? elixir needs a UTF locale, and `nix-shell --pure` tries to use an ANSI locale, so we do have to override it.

**Comment by iggi42** [comment]
```sh
echo $LC_CTYPE
echo $LC_COLLATE
echo $LC_MESSAGES
echo $LC_NUMERIC
echo $LC_TIME
```
are all not set.

outside of nix-shell:
```
[user@dev-privat tmp]$ cat /etc/locale.conf 
LANG=C.UTF-8
```

inside a `nix-shell --pure`:
```sh
[nix-shell:~/Code/remote/github.com/Belethors-General-Mods/belethor]$ echo $LANG
en_US.UTF-8
```

sounds like I don't have 'C.UTF-8' in nix, but 'en_US.UTF-8'.

**Comment by skwerlman** [comment]
i guess it should be possible to set up an `if` chain in the setup hook to try to set the locale to something that exists. or maybe there's a way to generate the locale every time? that'd probably be the more correct solution if i can figure out how to do it

**Comment by iggi42** [comment]
can we add `C.UTF-8` locale to `default.nix`?

**Comment by skwerlman** [comment]
we might be able to fix this with this: https://github.com/NixOS/nix/issues/318#issuecomment-52986702
can you edit locally to see if it works?

**Comment by skwerlman** [comment]
also see https://github.com/NixOS/nixpkgs/issues/20192 which would explain why its missing for you but not me (i'm on nixpkgs master)

**Comment by iggi42** [comment]
soo, all I should do is switch to nixpkgs master too?

**Comment by skwerlman** [comment]
i'd rather it worked on stable, but ye, switching to master would fix it

**Comment by iggi42** [comment]
switching to master, because of that is not worth it.
> does not impact anything thu, just a little annoying.

well, fuck it. time to merge.

**Comment by skwerlman** [comment]
make sure elixir can compile stuff before merging pls

**Comment by iggi42** [comment]
ofc, did I test that, before approving :)

**Pull request merged**
