### PR TITLE
npm audit fix

### PR DESCRIPTION
**Pull request by iggi42**
npm complained about security problems in brunch.
this should fix it (according to npm).

### CODE REVIEW

**Comment by skwerlman** [comment]
Do we want to maybe just switch to webpack since that's what phoenix is switching to?

**Comment by skwerlman** [comment]
I'm fine with this either way ofc

**Comment by iggi42** [comment]
maybe, I have no exp with both :)
I only tried to shut npm up.

**Review by skwerlman — APPROVED** [review]
should be fine to merge as-is; as discussed i'll take care of migrating to webpack later on.

**Pull request merged**
