### PR TITLE
add nixos postgres config snippet

### PR DESCRIPTION
**Pull request by iggi42**
add a nix snippet to setup a postgres database in NixOS for belethor.

### CODE REVIEW

**Review by skwerlman — CHANGES_REQUESTED** [review]
is there a reason this isn't part of default.nix? either way, to avoid accumulating platform-specific cruft in the root folder, can we move this to a nix subdirectory?

**Comment by iggi42** [comment]
well, the snippet is NixOS specific. It is meant to be copy pasted into /etc/nixos/configuration.nix
I can move the snippet into guides, something along "How to setup a dev environment".

default.nix is for getting a nix shell, it should stay in the root folder.

**Comment by skwerlman** [comment]
i do like this as a guide. now that its in the guide, can it be removed from the root dir? with that, it's good to merge imo

**Comment by iggi42** [comment]
> now that its in the guide, can it be removed from the root dir?

woops, I forgot to do that.

**Review by skwerlman — APPROVED** [review]

**Pull request merged**
